### ISSUE TITLE
Disable is not working

### ISSUE THREAD

**Issue by inakimalerba** [dnaextrim/python_zklib#12]
Hi ! Im using your lib to connect to my fingerprint reader, but I can't make the disable command work.

Any idea what it can be?

Thanks in advance

**Comment by fananimi** [comment]
@Inakimalerba you can try alternate solution by using pyzk. http://pyzk.readthedocs.io/en/stable/

**Comment by Inakimalerba** [comment]
Thank you @fananimi , I'll give it a try !
